"""
Build a single self-contained HTML dashboard you can open in a browser
(no server, no cost). It shows the underlying carbon-market data, the weekly
snapshot, per-asset paper-backtest equity curves, and the honest IS/OOS
research verdict — all charts embedded as base64.

Usage:
    python dashboard.py
    # -> out/dashboard.html   (double-click to open in your browser)
"""

from __future__ import annotations

import base64
import io
import os
from datetime import date

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from backtest import load, signal
from carbon_report import fetch, metrics
from research import run_research

OUT = "out"


def _png_b64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120, bbox_inches="tight")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


def _price_chart(close: pd.DataFrame) -> str:
    norm = close / close.iloc[0] * 100
    fig = plt.figure(figsize=(9, 4))
    for c in norm.columns:
        plt.plot(norm.index, norm[c], label=c, lw=1.4)
    plt.title("Carbon ETFs — normalized to 100")
    plt.legend()
    plt.grid(alpha=0.3)
    return _png_b64(fig)


def _equity_chart(ticker: str) -> str | None:
    px = load(ticker)
    if len(px) < 100:
        return None
    ret = px.pct_change().fillna(0)
    sig = signal(px)
    eq_s = (1 + sig * ret).cumprod()
    eq_b = (1 + ret).cumprod()
    fig = plt.figure(figsize=(9, 3.6))
    plt.plot(eq_s.index, eq_s, label="Signal (long/flat)", lw=1.6)
    plt.plot(eq_b.index, eq_b, label="Buy & Hold", lw=1.2, alpha=0.8)
    plt.title(f"{ticker} — signal vs buy & hold (paper)")
    plt.ylabel("Growth of $1")
    plt.legend()
    plt.grid(alpha=0.3)
    return _png_b64(fig)


def _table(df_rows, cols) -> str:
    head = "".join(f"<th>{c}</th>" for c in cols)
    body = ""
    for r in df_rows:
        cells = "".join(f"<td>{r[c]}</td>" for c in cols)
        body += f"<tr>{cells}</tr>"
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def main() -> None:
    import sys

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    os.makedirs(OUT, exist_ok=True)
    close = fetch("1y")
    m = metrics(close)
    m_rows = [{"ticker": idx, **{c: m.loc[idx, c] for c in m.columns}} for idx in m.index]
    m_cols = ["ticker"] + list(m.columns)

    price_img = _price_chart(close)
    eq_imgs = [(tk, _equity_chart(tk)) for tk in ["KRBN", "KCCA", "GRN"]]
    rows, _ = run_research()
    r_cols = list(rows[0].keys()) if rows else []
    wins = sum(1 for r in rows if r["verdict"] == "WIN")

    eq_html = ""
    for tk, img in eq_imgs:
        if img:
            eq_html += f'<img src="data:image/png;base64,{img}" alt="{tk}"/>'

    html = f"""<!doctype html><html lang="ko"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Carbon Market Dashboard</title>
<style>
 body{{font-family:system-ui,Segoe UI,Roboto,sans-serif;max-width:960px;margin:24px auto;padding:0 16px;color:#1a1a1a}}
 h1{{margin-bottom:2px}} .sub{{color:#666;margin-top:0}}
 h2{{margin-top:32px;border-bottom:2px solid #eee;padding-bottom:6px}}
 img{{width:100%;border:1px solid #eee;border-radius:8px;margin:8px 0}}
 table{{border-collapse:collapse;width:100%;font-size:14px;margin:8px 0}}
 th,td{{border:1px solid #e2e2e2;padding:6px 10px;text-align:right}}
 th:first-child,td:first-child{{text-align:left}}
 th{{background:#f7f7f7}}
 .note{{background:#fff8e1;border:1px solid #ffe082;padding:10px 14px;border-radius:8px;font-size:14px}}
 .win{{color:#1b7a1b;font-weight:600}} .lose{{color:#b00020;font-weight:600}}
 footer{{color:#888;font-size:12px;margin-top:40px}}
</style></head><body>
<h1>Carbon Market Dashboard</h1>
<p class="sub">EU · 글로벌 · 캘리포니아 탄소배출권 — 데이터 · 백테스트 · 정직한 검증 · {date.today().isoformat()}</p>

<h2>1. 시장 데이터 (Snapshot)</h2>
{_table(m_rows, m_cols)}
<img src="data:image/png;base64,{price_img}" alt="prices"/>

<h2>2. 페이퍼 백테스트 — 시그널 vs Buy&amp;Hold</h2>
<p>브로커·돈 없이 시그널을 과거 데이터에 돌린 결과. 위=시그널 전략, 아래=단순 보유.</p>
{eq_html}

<h2>3. 정직한 검증 — 인샘플 최적화 → 아웃샘플 성과</h2>
<p>과거 60%에서 최적 파라미터를 고른 뒤, 못 본 40%에서의 성과. 진짜 시그널이면 아웃샘플에서도 이겨야 함.</p>
{_table([{**r, "verdict": ("<span class='win'>WIN</span>" if r["verdict"] == "WIN" else "<span class='lose'>LOSE</span>")} for r in rows], r_cols)}
<p class="note">결론: {len(rows)}개 자산 중 <b>{wins}개만</b> 아웃샘플에서 buy&amp;hold를 이김.
IS Sharpe가 OOS에서 급락 → 전형적 과최적화. <b>단순 추세/모멘텀 시그널은 견고하지 않음.</b>
따라서 이 제품은 '마법의 시그널'이 아니라 <b>탄소시장 정보·분석(시간 절약)</b>으로 포지셔닝하는 것이 정직하고 지속가능합니다.</p>

<footer>Data: Yahoo Finance (carbon-allowance ETFs). Paper backtest, no costs/slippage.
교육·리서치용, 투자 자문 아님. Generated by dashboard.py.</footer>
</body></html>"""

    path = os.path.join(OUT, "dashboard.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Wrote {path}  ({len(html)//1024} KB) — 브라우저로 열어보세요.")


if __name__ == "__main__":
    main()
